name: Monitoring Tagging nonprod

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!**/ram/**'

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      - name: set branch name
        id: currbranch
        shell: bash
        run: echo ::set-output name=BRANCH_NAME::$(git rev-parse --abbrev-ref HEAD)
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branches: |
            ['${{steps.currbranch.outputs.BRANCH_NAME}}']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: info@metro.digital
          GIT_COMMITTER_NAME: metro-digital-bot
          GIT_COMMITTER_EMAIL: info@metro.digital
