name: Tagging prod

on: 
  push:
    branches: 
      - 'master'

jobs: 
  tag:
    runs-on: ubuntu-latest
    name: Tag latest prod release
    steps:
    - name: analyse and push
      id: settag
      shell: bash
      run: |
        version=$(git describe --tags $(git rev-list --tags --max-count=1)|sed 's/nonprod/prod/g')
        hub tag "${version}" HEAD
        hub push origin "${version}"
