# ram release workflow
name: Ram Prod Tagging

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/ram/**'

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:            
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set branch name
        id: setbranch
        shell: bash
        run: |
          echo version=$(git remote update $(git describe --abbrev=0 --tags)|sed 's/nonprod/prod/g')
          hub tag "${version}" HEAD
          hub push origin "${version}"

#      - name: cleanup bad tag
#        uses: actions/github-script@v3
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}          
#          script: |
#            github.git.deleteRef({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              ref: "tags/${{ steps.tag_version.outputs.new_tag }}"
#            })

