# ram release workflow
name: Ram Prod Tagging

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '**/ram/**'

jobs:  
  build:    
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash
        working-directory: ./.github/ram/
    steps:            
      - uses: actions/checkout@v2
      - name: set branch name
        id: setbranch
        shell: bash
        run: echo ::set-output name=BRANCH_NAME::$(git rev-parse --abbrev-ref HEAD)
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          tag_prefix: "ram-v"
          append_to_pre_release_tag: "prod"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: set branch name
        id: setbranch
        shell: bash
        run: |
          echo
          version=$(echo ${{steps.tag_version.outputs.new_tag}} | awk '{ print substr( $0, 1, length($0)-2 ) }')
          hub tag "${version}" HEAD
          hub push origin "${version}"
#          hub tag -d :refs/tags/${{ steps.tag_version.outputs.new_tag }}

# -----------------------------
#      - run: |
#          hub tag -d ${{ steps.tag_version.outputs.new_tag }}
#          hub push origin #:refs/tags/${{ steps.tag_version.outputs.new_tag }}
